# Задание 40
Реализуйте метод крутого спуска на Python и найдите минимум функции:

$
f(y) = (Ay, y) - 2(b, y), \quad \text{где } y, b \in \mathbb{R}^6,
$

с

$$
A = \begin{pmatrix} 
4 & -1 & 0 & -1 & 0 & 0 \\
-1 & 4 & -1 & 0 & -1 & 0 \\
0 & -1 & 4 & 0 & 0 & -1 \\
-1 & 0 & 0 & 4 & -1 & 0 \\
0 & -1 & 0 & -1 & 4 & -1 \\
0 & 0 & -1 & 0 & -1 & 4 
\end{pmatrix},
\quad
b = \begin{pmatrix} 0 \\\\ 5 \\\\ 0 \\\ 6 \\\\ -2 \\\ 6 \end{pmatrix}.
$$

Вам разрешено использовать матричные и векторные операции. Использование готового функционала с реализованными методами оптимизации не допускается.

Ответ дайте с точностью до четырех знаков после запятой, указав $||0X^*||_2$, где $X^*$ - точка экстремума.

## Идея:

Для решения этой задачи нам нужно реализовать метод градиентного спуска (крутого спуска) в Python, чтобы найти минимум заданной квадратичной функции $f(y)$, определенной как:

$$
f(y) = (Ay, y) - 2(b, y)
$$

где:

- $y, b \in \mathbb{R}^6$,
- $A$ - $6 \times 6$ симметричная матрица,
- $ b $ - вектор в $ \mathbb{R}^6 $,
- $ (Ay, y)$ обозначает квадратичную форму (по сути $ y^T A y $),
- $ (b, y)$ - точечное произведение $ b^T y $.

### Шаги к решению:

1. **Определите функцию $ f(y) $:**.
- Функция может быть записана в терминах матрично-векторных операций как:
$$
f(y) = y^T A y - 2 b^T y
$$

2. **Вычислите градиент $ f(y)$:**.
- Градиент $ f(y)$ относительно $ y $ равен:
$$
\nabla f(y) = 2Ay - 2b
$$

3. **Выполните алгоритм градиентного спуска:**.
- Выбираем начальное предположение $ y_0 $.
- Установите скорость обучения $ \alpha $ (размер шага).
- Обновляем оценку итеративно, используя:
$$
y_{k+1} = y_k - \alpha \nabla f(y_k)
$$
- Продолжаем итерации до сходимости (когда норма градиента достаточно мала).

4. **Вычислить норму вектора решения $ y^* $:**.
- Когда оптимальное значение $ y^* $ найдено, вычислите $ \|y^*\|_2 $, евклидову норму $ y^* $, и округлите результат до четырех знаков после запятой.


In [1]:
import numpy as np
from typing import List

# Константы для градиентного спуска
MAX_ITERATIONS: int = 100_000   # Максимальное количество итераций
ALPHA: float = 0.01             # Шаг градиентного спуска
TOLERANCE: float = 1e-6         # Порог для остановки алгоритма (точность)
SIZE: int = 6                   # Размерность вектора


def load_A() -> np.ndarray:
    """
    Загружает матрицу A из текстового файла и преобразует её в numpy array.

    Returns:
        np.ndarray: Матрица A размера (6, 6).
    """
    with open('40/A.txt', 'r') as f:
        data = f.readlines()

    # Преобразование строк в целочисленную матрицу
    data = [list(map(int, line.split())) for line in data]
    return np.array(data)


def load_B() -> np.ndarray:
    """
    Загружает вектор B из текстового файла и преобразует его в numpy array.

    Returns:
        np.ndarray: Вектор B размера (6,).
    """
    with open('40/B.txt', 'r') as f:
        data = f.readline().split()
    return np.array(list(map(int, data)))


def solution(A: np.ndarray, B: np.ndarray) -> float:
    """
    Реализует метод градиентного спуска для нахождения минимального значения функции
    f(y) = (Ay, y) - 2(b, y) и вычисляет норму результата ||y*||_2 с точностью до 6 знаков.

    Args:
        A (np.ndarray): Матрица размера (6, 6).
        B (np.ndarray): Вектор размера (6,).

    Returns:
        float: Евклидова норма оптимального вектора y*, округленная до 6 знаков.
    """
    # Инициализация начальной точки y
    y = np.zeros(SIZE)

    # Градиентный спуск
    for _ in range(MAX_ITERATIONS):
        grad = 2 * A @ y - 2 * B  # Вычисление градиента

        # Условие остановки по норме градиента
        if np.linalg.norm(grad) < TOLERANCE:
            break

        # Шаг обновления y
        y = y - ALPHA * grad

    # Нахождение нормы оптимального y и округление до 6 знаков
    norm_y_star = np.linalg.norm(y)
    norm_y_star_rounded = round(norm_y_star, 6)
    return norm_y_star_rounded


if __name__ == '__main__':
    A = load_A()
    B = load_B()

    print('=' * 50)
    print(f'Матрица A:\n{A}')
    print(f'Вектор B: {B}\n')
    print(
        f'Параметры запуска:\nalpha={ALPHA}, max_iter={MAX_ITERATIONS}, tolerance={TOLERANCE}\nРезультат: {solution(A, B)}'
    )
    print('=' * 50)


Матрица A:
[[ 4 -1  0 -1  0  0]
 [-1  4 -1  0 -1  0]
 [ 0 -1  4  0  0 -1]
 [-1  0  0  4 -1  0]
 [ 0 -1  0 -1  4 -1]
 [ 0  0 -1  0 -1  4]]
Вектор B: [ 0  5  0  6 -2  6]

Параметры запуска:
alpha=0.01, max_iter=100000, tolerance=1e-06
Результат: 3.872983


# Задание 41

По данным измерения двух переменных напишите приложение для нахождения уравнения линейной  регрессии $Y$ на  $Х$.  В  ответе  укажите  сумму  модулей найденных параметров.

| X | 51 | 67 | 84 | 81 | 101 | 71 | 97 | 109 | 51 | 105 | 89 |
|---|----|----|----|----|-----|----|----|-----|----|-----|----|
| Y | 25 | 30 | 43 | 57 | 58  | 43 | 46 | 62  | 45 | 55  | 45 |


Для решения этой задачи мы можем использовать метод наименьших квадратов, чтобы найти параметры линейной регрессии $ Y = aX + b $. Затем мы рассчитаем сумму модулей найденных параметров $ a $ и $ b $.

Вот шаги, которые нужно выполнить:

1. **Загрузить данные** для переменных $ X $ и $ Y $.
2. **Вычислить коэффициенты линейной регрессии** $ a $ (наклон) и $ b $ (сдвиг), используя формулы для метода наименьших квадратов:
   $$
   a = \frac{n \sum(XY) - \sum(X) \sum(Y)}{n \sum(X^2) - (\sum X)^2}
   $$
   $$
   b = \frac{\sum(Y) - a \sum(X)}{n}
   $$
   где $ n $ — количество точек (размер массива $ X $ или $ Y $).
3. **Вычислить сумму модулей** $ |a| + |b| $ и вывести результат.


In [2]:
import numpy as np
from typing import Tuple


def load_data() -> Tuple[np.ndarray, np.ndarray]:
    """
    Загружает данные из текстового файла, содержащего два ряда чисел,
    и преобразует их в массивы numpy.

    Предполагается, что файл `dataset.txt` содержит два ряда чисел:
    - Первая строка — значения X
    - Вторая строка — значения Y

    Returns:
        Tuple[np.ndarray, np.ndarray]: Кортеж из двух массивов numpy:
        - x: массив значений X (независимая переменная)
        - y: массив значений Y (зависимая переменная)
    """
    with open('41/dataset.txt', 'r') as f:
        x, y = f.readlines()

    # Преобразование строк в массивы целых чисел
    x = list(map(int, x.strip().split(' ')))
    y = list(map(int, y.strip().split(' ')))

    return np.array(x), np.array(y)


def solution(x: np.ndarray, y: np.ndarray, n: int) -> Tuple[float, float, float]:
    """
    Вычисляет параметры линейной регрессии y = ax + b для заданных массивов X и Y
    методом наименьших квадратов, а также возвращает сумму модулей параметров a и b.

    Args:
        x (np.ndarray): Массив значений независимой переменной X.
        y (np.ndarray): Массив значений зависимой переменной Y.
        n (int): Количество точек данных (размер массива X или Y).

    Returns:
        Tuple[float, float, float]: Кортеж, содержащий:
        - a: коэффициент наклона (параметр при X)
        - b: свободный член (сдвиг)
        - abs(a) + abs(b): сумма модулей коэффициентов a и b
    """
    # Вычисление коэффициента наклона a
    a = (n * np.sum(x * y) - np.sum(x) * np.sum(y)) / \
        (n * np.sum(x**2) - (np.sum(x))**2)
    # Вычисление свободного члена b
    b = (np.sum(y) - a * np.sum(x)) / n

    # Возврат значений a, b и их суммы модулей
    return a, b, abs(a) + abs(b)


if __name__ == '__main__':
    x, y = load_data()
    n = len(x)
    a, b, sol = solution(x, y, n)

    print('=' * 50)
    print(f'Начальные данные:\nx -> {x}\ny -> {y}\n')
    print(f'Найденные параметры:\na -> {a} b -> {b}')
    print(f'Сумма модулей параметров: {round(sol, 6)}')
    print('=' * 50)


Начальные данные:
x -> [ 51  67  84  81 101 109  71  97 109  51 105  89]
y -> [25 30 43 44 57 58 43 46 62 45 55 45]

Найденные параметры:
a -> 0.43893109953443293 b -> 8.95707783104588
Сумма модулей параметров: 9.396009


# Задание 42
Считая, что зависимость между переменными $X$ и $Y$ имеет вид  

$$
y=\sum\limits_{j=0}^{m} \beta_{j}x^j{}
$$
 
напишите приложение для нахождения оценок параметров $\beta_0,\beta_1,\dots, \beta_m$  по следующей выборке ($m$ − натуральный параметр, определяемый пользователем). 
|X|0,5|1,0|1,5|2,0|2,5|3,0|3,5|4,0|
|-|-|-|-|-|-|-|-|-|
|Y|0,4|0,3|1,0|1,7|2,1|3,4|4,1|5,8|

продолжение
|4,5|5,0|5,5|6,0|6,5|7,0|7,5|8,0|
|-|-|-|-|-|-|-|-|
|7,7|9,4|11,4|13,6|15,6|18,6|21,2|24,1|


Для нахождения коэффициентов $\beta_0, \beta_1, \dots, \beta_m$ уравнения $ y = \sum_{j=0}^{m} \beta_j x^j $ по заданной выборке $ (X, Y) $, мы можем воспользоваться полиномиальной регрессией. В этом случае уравнение принимает вид многочлена степени $ m $, который мы аппроксимируем к данным методом наименьших квадратов.

### Решение:
1. **Подготовка данных**: Создадим массивы для $ X $ и $ Y $ на основе данных в таблице.
2. **Формирование системы уравнений**: Построим матрицу, в которой каждая строка будет содержать степени элементов $ X $ до $ m $-й степени.
3. **Метод наименьших квадратов**: Используем функцию `np.linalg.lstsq` из библиотеки NumPy для решения системы линейных уравнений, что позволит найти значения параметров $\beta_j$.
4. **Вывод коэффициентов**: Выведем найденные значения $\beta_j$.


In [3]:
import numpy as np
from typing import List, Tuple


def load_data() -> Tuple[np.ndarray, np.ndarray]:
    """
    Загружает данные из текстового файла, содержащего два ряда чисел,
    и преобразует их в массивы numpy.

    Предполагается, что файл `dataset.txt` содержит два ряда чисел:
    - Первая строка — значения X
    - Вторая строка — значения Y

    Returns:
        Tuple[np.ndarray, np.ndarray]: Кортеж из двух массивов numpy.
    """
    with open('42/dataset.txt', 'r') as f:
        x, y = f.readlines()

    # Преобразование строк в массивы целых чисел
    x = list(map(float, x.strip().split(' ')))
    y = list(map(float, y.strip().split(' ')))

    return np.array(x), np.array(y)


def polynomial_regression(X: np.ndarray, Y: np.ndarray, m: int) -> List[float]:
    """
    Выполняет полиномиальную регрессию степени m для данных X и Y, чтобы найти коэффициенты β_j.

    Args:
        X (np.ndarray): Массив значений X.
        Y (np.ndarray): Массив значений Y.
        m (int): Степень полинома.

    Returns:
        List[float]: Список коэффициентов β_j, начиная с β_0.
    """
    # Создаем матрицу Вандермонда для X, чтобы включить степени до m
    X_vander = np.vander(X, m + 1, increasing=True)

    # Решаем линейную систему для нахождения коэффициентов
    beta, *_ = np.linalg.lstsq(X_vander, Y, rcond=None)

    return beta.tolist()


if __name__ == '__main__':
    X, Y = load_data()

    print('=' * 50)
    m = int(input("Введите степень полинома m: "))
    beta = polynomial_regression(X, Y, m)

    # Вывод коэффициентов
    print("Найденные коэффициенты β_j:")
    for j, coeff in enumerate(beta):
        print(f"β_{j} = {coeff:.6f}")

    # Сумма модулей коэффициентов
    sum_abs_beta = sum(abs(b) for b in beta)
    print(f"\nСумма модулей коэффициентов: {sum_abs_beta:.4f}")
    print('=' * 50)

Найденные коэффициенты β_j:
β_0 = 0.133654
β_1 = 0.347994
β_2 = -0.058410
β_3 = 0.143233
β_4 = -0.018596
β_5 = 0.000848

Сумма модулей коэффициентов: 0.7027


# Задане 43
Напишите приложение для нахождения оценок параметров модели  
$ y= \beta_0 + \beta_1 \ln x $ по следующей выборке:

|X|1|2|3|4|5|6|7|8|9|10|11|12|
|-|-|-|-|-|-|-|-|-|-|--|--|--|
|Y|2.11|2.45|2.61|2.73|2.75|2.81|2.87|2.91|2.96|3.03|3.05|3.12|

Для нахождения коэффициентов модели $ y = \beta_0 + \beta_1 \ln(x) $ по заданной выборке $ (X, Y) $, мы можем воспользоваться линейной регрессией. Для этого мы применим логарифмическое преобразование к $ X $, чтобы модель стала линейной относительно параметров $\beta_0$ и $\beta_1$.

### Решение
1. **Преобразование данных**: Преобразуем $ X $ с помощью функции логарифма, получив $ \ln(X) $.
2. **Линейная регрессия**: Построим линейную регрессию для $ Y $ и $\ln(X)$ с помощью метода наименьших квадратов, чтобы найти значения $\beta_0$ и $\beta_1$.
3. **Вывод коэффициентов**: Выведем найденные значения $\beta_0$ и $\beta_1$.


In [4]:
import numpy as np
from typing import Tuple, List


def load_data() -> Tuple[np.ndarray, np.ndarray]:
    """
    Загружает данные из текстового файла, содержащего два ряда чисел,
    и преобразует их в массивы numpy.

    Предполагается, что файл `dataset.txt` содержит два ряда чисел:
    - Первая строка — значения X
    - Вторая строка — значения Y

    Returns:
        Tuple[np.ndarray, np.ndarray]: Кортеж из двух массивов numpy.
    """
    with open('43/dataset.txt', 'r') as f:
        x, y = f.readlines()

    # Преобразование строк в массивы целых чисел
    x = list(map(float, x.strip().split(' ')))
    y = list(map(float, y.strip().split(' ')))

    return np.array(x), np.array(y)


def logarithmic_regression(X: np.ndarray, Y: np.ndarray) -> Tuple[float, float]:
    """
    Выполняет линейную регрессию для модели y = β0 + β1 * ln(x),
    используя логарифмическое преобразование X.

    Args:
        X (np.ndarray): Массив значений независимой переменной X.
        Y (np.ndarray): Массив значений зависимой переменной Y.

    Returns:
        Tuple[float, float]: Кортеж, содержащий параметры:
        - β0 (свободный член)
        - β1 (коэффициент при ln(x))
    """
    # Преобразование X в логарифмические значения
    X_log = np.log(X)

    # Решение задачи линейной регрессии Y = β0 + β1 * X_log
    A = np.vstack([np.ones_like(X_log), X_log]).T
    beta, _ = np.linalg.lstsq(A, Y, rcond=None)[0:2]

    return beta[0], beta[1]


if __name__ == '__main__':
    X, Y = load_data()

    beta_0, beta_1 = logarithmic_regression(X, Y)

    print('=' * 50)
    print(f"Найденные коэффициенты модели y = β0 + β1 * ln(x):")
    print(f"β0 = {beta_0:.6f}")
    print(f"β1 = {beta_1:.6f}")

    sum_abs_beta = abs(beta_0) + abs(beta_1)
    print(f"\nСумма модулей коэффициентов: {sum_abs_beta:.4f}")
    print('=' * 50)


Найденные коэффициенты модели y = β0 + β1 * ln(x):
β0 = 2.157045
β1 = 0.376013

Сумма модулей коэффициентов: 2.5331


# Задание 44

Напишите приложение для нахождения оценок параметров модели $y=\beta_0+\beta_1e^{0.1x}$ по следующей выборке.

|X|1|2|3|4|5|6|7|8|9|10|11|12|
|-|-|-|-|-|-|-|-|-|-|--|--|--|
|Y|0.10|0.21|0.43|0.51|0.62|0.81|1.01|1.23|1.47|1.53|1.75|2.25|


Для нахождения коэффициентов модели $ y = \beta_0 + \beta_1 e^{0.1x} $ по заданной выборке $ (X, Y) $, мы можем воспользоваться линейной регрессией с использованием преобразования независимой переменной $ X $. Преобразуем модель так, чтобы она была линейной по параметрам $\beta_0$ и $\beta_1$.

В этом случае мы будем рассматривать $ z = e^{0.1x} $ как новую переменную, и перепишем модель как:
$$ y = \beta_0 + \beta_1 z $$
где $ z = e^{0.1x} $.

### Шаги решения
1. **Преобразование данных**: Рассчитаем $ z = e^{0.1x} $ для каждого значения $ x $ в массиве $ X $.
2. **Линейная регрессия**: Построим линейную регрессию для $ Y $ и $ z $ (т.е., найдем $\beta_0$ и $\beta_1$ в линейной модели $ y = \beta_0 + \beta_1 z $).
3. **Вывод коэффициентов**: Выведем значения $\beta_0$ и $\beta_1$ и сумму модулей коэффициентов.


In [5]:
import numpy as np
from typing import Tuple


def load_data() -> Tuple[np.ndarray, np.ndarray]:
    """
    Загружает данные из текстового файла, содержащего два ряда чисел,
    и преобразует их в массивы numpy.

    Предполагается, что файл `dataset.txt` содержит два ряда чисел:
    - Первая строка — значения X
    - Вторая строка — значения Y

    Returns:
        Tuple[np.ndarray, np.ndarray]: Кортеж из двух массивов numpy.
    """
    with open('44/dataset.txt', 'r') as f:
        x, y = f.readlines()

    # Преобразование строк в массивы целых чисел
    x = list(map(float, x.strip().split(' ')))
    y = list(map(float, y.strip().split(' ')))

    return np.array(x), np.array(y)


def exponential_regression(X: np.ndarray, Y: np.ndarray) -> Tuple[float, float]:
    """
    Выполняет линейную регрессию для модели y = β0 + β1 * exp(0.1 * x),
    используя экспоненциальное преобразование X.

    Args:
        X (np.ndarray): Массив значений независимой переменной X.
        Y (np.ndarray): Массив значений зависимой переменной Y.

    Returns:
        Tuple[float, float]: Кортеж, содержащий параметры:
        - β0 (свободный член)
        - β1 (коэффициент при exp(0.1 * x))
    """
    # Преобразование X в экспоненциальные значения
    Z = np.exp(0.1 * X)

    # Создаем матрицу для линейной регрессии
    A = np.vstack([np.ones_like(Z), Z]).T

    # Решение задачи линейной регрессии Y = β0 + β1 * Z
    beta, _ = np.linalg.lstsq(A, Y, rcond=None)[0:2]

    return beta[0], beta[1]


if __name__ == '__main__':
    # Загрузка данных
    X, Y = load_data()

    # Нахождение коэффициентов
    beta_0, beta_1 = exponential_regression(X, Y)

    # Вывод коэффициентов
    print('=' * 50)
    print(f"Найденные коэффициенты модели y = β0 + β1 * exp(0.1 * x):")
    print(f"β0 = {beta_0:.6f}")
    print(f"β1 = {beta_1:.6f}")

    # Сумма модулей коэффициентов
    sum_abs_beta = abs(beta_0) + abs(beta_1)
    print(f"\nСумма модулей коэффициентов: {sum_abs_beta:.6f}")
    print('=' * 50)


Найденные коэффициенты модели y = β0 + β1 * exp(0.1 * x):
β0 = -0.862627
β1 = 0.913495

Сумма модулей коэффициентов: 1.776122


# Задание 45
Напишите приложение для нахождения оценок параметров модели $y=\beta_0 + \beta_1x + \beta_2\sin(8x)$ по следующей выборке.

|X|2.11|2.45|2.61|2.73|2.75|2.81|2.87|2.91|2.96|3.03|3.05|3.12|
|-|-|-|-|-|-|-|-|-|-|-|-|-|
|Y|0.10|0.21|0.43|0.51|0.62|0.81|1.01|1.23|1.47|1.53|1.75|2.25|

Для нахождения коэффициентов модели $ y = \beta_0 + \beta_1 x + \beta_2 \sin(8x) $ по заданной выборке, можно воспользоваться линейной регрессией с преобразованием переменных. В этом случае модель остается линейной по параметрам $\beta_0$, $\beta_1$ и $\beta_2$, что позволяет применить метод наименьших квадратов.

### Шаги решения
1. **Преобразование данных**: Создадим дополнительные столбцы для регрессии:
   - $ x $, для нахождения коэффициента $\beta_1$,
   - $ \sin(8x) $, для нахождения коэффициента $\beta_2$.
   
2. **Линейная регрессия**: Используем матрицу признаков для выполнения линейной регрессии и нахождения коэффициентов $\beta_0$, $\beta_1$ и $\beta_2$.
   
3. **Вывод коэффициентов**: Выведем найденные значения параметров $\beta_0$, $\beta_1$ и $\beta_2$, а также сумму модулей коэффициентов.


In [6]:
import numpy as np
from typing import Tuple


def load_data() -> Tuple[np.ndarray, np.ndarray]:
    """
    Загружает данные из текстового файла, содержащего два ряда чисел,
    и преобразует их в массивы numpy.

    Предполагается, что файл `dataset.txt` содержит два ряда чисел:
    - Первая строка — значения X
    - Вторая строка — значения Y

    Returns:
        Tuple[np.ndarray, np.ndarray]: Кортеж из двух массивов numpy.
    """
    with open('45/dataset.txt', 'r') as f:
        x, y = f.readlines()

    # Преобразование строк в массивы целых чисел
    x = list(map(float, x.strip().split(' ')))
    y = list(map(float, y.strip().split(' ')))

    return np.array(x), np.array(y)


def regression_with_sine(X: np.ndarray, Y: np.ndarray) -> Tuple[float, float, float]:
    """
    Выполняет линейную регрессию для модели y = β0 + β1 * x + β2 * sin(8 * x).

    Args:
        X (np.ndarray): Массив значений независимой переменной X.
        Y (np.ndarray): Массив значений зависимой переменной Y.

    Returns:
        Tuple[float, float, float]: Кортеж, содержащий параметры:
        - β0 (свободный член),
        - β1 (коэффициент при x),
        - β2 (коэффициент при sin(8 * x))
    """
    # Создаем столбцы для регрессии: [1, x, sin(8x)]
    A = np.vstack([np.ones_like(X), X, np.sin(8 * X)]).T

    # Решаем линейную систему Y = A @ [β0, β1, β2]
    beta, _, _, _ = np.linalg.lstsq(A, Y, rcond=None)

    return beta[0], beta[1], beta[2]


if __name__ == '__main__':
    # Загрузка данных
    X, Y = load_data()

    # Нахождение коэффициентов
    beta_0, beta_1, beta_2 = regression_with_sine(X, Y)

    # Вывод коэффициентов
    print('=' * 50)
    print("Найденные коэффициенты модели y = β0 + β1 * x + β2 * sin(8 * x):")
    print(f"β0 = {beta_0:.6f}")
    print(f"β1 = {beta_1:.6f}")
    print(f"β2 = {beta_2:.6f}")

    # Сумма модулей коэффициентов
    sum_abs_beta = abs(beta_0) + abs(beta_1) + abs(beta_2)
    print(f"\nСумма модулей коэффициентов: {sum_abs_beta:.6f}")
    print('=' * 50)


Найденные коэффициенты модели y = β0 + β1 * x + β2 * sin(8 * x):
β0 = -4.494369
β1 = 1.947397
β2 = -0.198925

Сумма модулей коэффициентов: 6.640691


# Задание 46

Преобразование  строк  матрицы,  основанное  на  исключении  неизвестных (приведении к треугольному виду), используется при вычислении определителя, поиска  решений  системы  линейных  алгебраических  уравнений,  нахождении обратной матрицы, вычислении ранга матрицы.

Разработайте  приложение,  в  котором  разработана  функция,  реализующая это преобразование. С помощью этой функции реализуйте методы вычисления определителя  квадратной  матрицы,  нахождения  обратной  матрицы,  поиска единственного решения системы линейных алгебраических уравнений, проверку совместности системы с помощью теоремы Кронекера-Капелли. Ваша программа на  вход  получает  файл,  в  котором  содержаться  матрицы  или  системы (размерность,  количество  матриц  или  систем  произвольно  и  не  фиксировано). 
Элементы матриц записаны построчно. 

```bash
A=(2 5 7; 6 3 4; 5 -2 -3) 
% 
A=(2 3 -1; 1 -2 1; 1 0 2) 
B=(9 3 2) 
%
```

Записи  разделяются  `%`.  Если  запись  содержит  только  матрицу,  то  для  этой матрицы, если это возможно, необходимо найти определитель, обратную матрицу, ранг матрицы. Если запись содержит матрицу и вектор свободных слагаемых, то данная запись соответствует СЛАУ. Для заданной системы необходимо проверить совместность, если решение единственно, найти это решение методом Гаусса.

Результатом работы вашей программы является файл, в котором для каждой записи  из  исходного  файла  приведен  результат  нахождения  соответствующих задач.